In [ ]:
import pandas as pd
import numpy as np
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

ImportError: ignored

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/BTP/ecommerceDataset.csv')

In [ ]:
df

Household  \
0        Household   
1        Household   
2        Household   
3        Household   
4        Household   
...            ...   
50419  Electronics   
50420  Electronics   
50421  Electronics   
50422  Electronics   
50423  Electronics   

      Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
0      SAF 'Floral' Framed Painting (Wood, 30 inch x ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
1      SAF 'UV Textured Modern Art Print Framed' Pain...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [ ]:
df.columns = ['Category','Text']

KeyError: ignored

In [ ]:
df

Category                                               Text
0        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2        Household  SAF Flower Print Framed Painting (Synthetic, 1...
3        Household  Incredible Gifts India Wooden Happy Birthday U...
4        Household  Pitaara Box Romantic Venice Canvas Painting 6m...
...            ...                                                ...
50419  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50420  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50421  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50422  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50423  Electronics                   Micromax Canvas Win W121 (White)

[50424 rows x 2 columns]

In [ ]:
df = df[['Category', 'Text']]
df = df.astype('str').applymap(str.lower)
df = df.applymap(str.strip).replace(r"[^a-z0-9 ]+", "")
df = df.dropna()
df = df.drop_duplicates()

In [ ]:
df

Category                                               Text
0        household  saf 'floral' framed painting (wood, 30 inch x ...
1        household  saf 'uv textured modern art print framed' pain...
2        household  saf flower print framed painting (synthetic, 1...
3        household  incredible gifts india wooden happy birthday u...
4        household  pitaara box romantic venice canvas painting 6m...
...            ...                                                ...
50401  electronics  micromax bharat 5 plus zero impact on visual d...
50402  electronics  microsoft lumia 550 8gb 4g black microsoft lum...
50406  electronics  microsoft lumia 535 (black, 8gb) colour:black ...
50407  electronics  karbonn titanium wind w4 (white) karbonn titan...
50409  electronics  nokia lumia 530 (dual sim, grey) colour:grey  ...

[27754 rows x 2 columns]

In [ ]:
df['Text']

0        saf 'floral' framed painting (wood, 30 inch x ...
1        saf 'uv textured modern art print framed' pain...
2        saf flower print framed painting (synthetic, 1...
3        incredible gifts india wooden happy birthday u...
4        pitaara box romantic venice canvas painting 6m...
                               ...                        
50401    micromax bharat 5 plus zero impact on visual d...
50402    microsoft lumia 550 8gb 4g black microsoft lum...
50406    microsoft lumia 535 (black, 8gb) colour:black ...
50407    karbonn titanium wind w4 (white) karbonn titan...
50409    nokia lumia 530 (dual sim, grey) colour:grey  ...
Name: Text, Length: 27754, dtype: object

In [ ]:
docs=np.array(df['Text'])

In [ ]:

docs


array(["saf 'floral' framed painting (wood, 30 inch x 10 inch, special effect uv print textured, sao297) painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. this is an special series of paintings which makes your wall very beautiful and gives a royal touch (a perfect gift for your special ones).",
       "saf 'uv textured modern art print framed' painting (synthetic, 35 cm x 50 cm x 3 cm, set of 3) color:multicolor                                                                                \xa0|\xa0                           size:35 cm x 50 cm x 3 cm   overview a beautiful painting involves the action or skill of using paint in the right manner; hence, the end product will be a picture that can speak a thousand words they say. arts have been in trend for quite some time now. it can give different viewer different meanings style and design the saf wood matte abstract painting with frame is quite abstract and mysteriously beaut

In [ ]:
df['Category'].unique()

array(['household', 'books', 'clothing & accessories', 'electronics'],
      dtype=object)

In [ ]:
sf=df['Category'].map({'household':0, 'electronics':1,'books':2,'clothing & accessories':3})

In [ ]:
sf=np.array(sf)

In [ ]:
sf

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
# pad documents to a max length of 20 words
max_length = 20
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[    3  5792    45 ...    10   342  1074]
 [   77  1192   448 ...     5  1841   566]
 [  148    36   475 ...     8     1   475]
 ...
 [ 6492    19    40 ...   237 24625   187]
 [  222   649   619 ...     2   544   247]
 [ 2939   730  2607 ...     4    42   581]]


In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2022-11-17 20:39:20--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2022-11-17 20:39:20--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2022-11-17 20:39:20--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [ ]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('/content/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = np.array(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [ ]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [ ]:
embedding_matrix

NameError: ignored

In [ ]:
padded_docs

NameError: ignored

In [ ]:
t.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'to': 4,
 'a': 5,
 'for': 6,
 'in': 7,
 'with': 8,
 'is': 9,
 'your': 10,
 'you': 11,
 'it': 12,
 'this': 13,
 'on': 14,
 'from': 15,
 'that': 16,
 'or': 17,
 'as': 18,
 'are': 19,
 'can': 20,
 '1': 21,
 'be': 22,
 'all': 23,
 'an': 24,
 '2': 25,
 'has': 26,
 'at': 27,
 'by': 28,
 '3': 29,
 'will': 30,
 'size': 31,
 'x': 32,
 'set': 33,
 '5': 34,
 'use': 35,
 'quality': 36,
 'book': 37,
 'not': 38,
 'easy': 39,
 'made': 40,
 'one': 41,
 'have': 42,
 'high': 43,
 'up': 44,
 'which': 45,
 'product': 46,
 'about': 47,
 '4': 48,
 'black': 49,
 'also': 50,
 'our': 51,
 'he': 52,
 'home': 53,
 'design': 54,
 'more': 55,
 'color': 56,
 'author': 57,
 'any': 58,
 'cotton': 59,
 'new': 60,
 'its': 61,
 'we': 62,
 'his': 63,
 'time': 64,
 'these': 65,
 '6': 66,
 'power': 67,
 'perfect': 68,
 'best': 69,
 'material': 70,
 'other': 71,
 'light': 72,
 'make': 73,
 'used': 74,
 'no': 75,
 'features': 76,
 'most': 77,
 'so': 78,
 'long': 79,
 'steel': 80,
 'look': 81,

In [ ]:

def embedding_for_vocab(filepath, word_index,
						embedding_dim):
	vocab_size = len(word_index) + 1
	
	# Adding again 1 because of reserved 0 index
	embedding_matrix_vocab = np.zeros((vocab_size,
									embedding_dim))

	with open(filepath, encoding="utf8") as f:
		for line in f:
			word, *vector = line.split()
			if word in word_index:
				idx = word_index[word]
				embedding_matrix_vocab[idx] = np.array(
					vector, dtype=np.float32)[:embedding_dim]

	return embedding_matrix_vocab


# matrix for vocab: word_index
embedding_dim = 100
embedding_matrix_vocab = embedding_for_vocab('/content/glove.6B.100d.txt', t.word_index,embedding_dim)

print("Dense vector for first word is => ",
	embedding_matrix_vocab[3])


Dense vector for first word is =>  [-0.1529     -0.24279     0.89837003  0.16996001  0.53516001  0.48784
 -0.58825999 -0.17982    -1.35810006  0.42541     0.15377     0.24214999
  0.13474     0.41192999  0.67043    -0.56418002  0.42985001 -0.012183
 -0.11677     0.31781     0.054177   -0.054273    0.35516    -0.30241001
  0.31434    -0.33846     0.71714997 -0.26855001 -0.15837    -0.47466999
  0.051581   -0.33252001  0.15003    -0.12989999 -0.54617    -0.37843001
  0.64261001  0.82187003 -0.080006    0.078479   -0.96976    -0.57740998
  0.56490999 -0.39873001 -0.057099    0.19743     0.065706   -0.48091999
 -0.20125    -0.40834001  0.39456001 -0.02642    -0.11838     1.01199996
 -0.53171003 -2.74740005 -0.042981   -0.74848998  1.75740004  0.59085
  0.04885     0.78267002  0.38497001  0.42096999  0.67882001  0.10337
  0.63279998 -0.026595    0.58647001 -0.44332001  0.33057001 -0.12022
 -0.55645001  0.073611    0.20915     0.43395001 -0.012761    0.089874
 -1.79910004  0.084808    0.7711

In [ ]:
embedding_matrix_vocab[3]

array([-0.1529    , -0.24279   ,  0.89837003,  0.16996001,  0.53516001,
        0.48784   , -0.58825999, -0.17982   , -1.35810006,  0.42541   ,
        0.15377   ,  0.24214999,  0.13474   ,  0.41192999,  0.67043   ,
       -0.56418002,  0.42985001, -0.012183  , -0.11677   ,  0.31781   ,
        0.054177  , -0.054273  ,  0.35516   , -0.30241001,  0.31434   ,
       -0.33846   ,  0.71714997, -0.26855001, -0.15837   , -0.47466999,
        0.051581  , -0.33252001,  0.15003   , -0.12989999, -0.54617   ,
       -0.37843001,  0.64261001,  0.82187003, -0.080006  ,  0.078479  ,
       -0.96976   , -0.57740998,  0.56490999, -0.39873001, -0.057099  ,
        0.19743   ,  0.065706  , -0.48091999, -0.20125   , -0.40834001,
        0.39456001, -0.02642   , -0.11838   ,  1.01199996, -0.53171003,
       -2.74740005, -0.042981  , -0.74848998,  1.75740004,  0.59085   ,
        0.04885   ,  0.78267002,  0.38497001,  0.42096999,  0.67882001,
        0.10337   ,  0.63279998, -0.026595  ,  0.58647001, -0.44

In [ ]:
embedding_matrix_vocab[padded_docs[0][2]]

array([ 3.02399993e-02,  4.46060002e-01,  4.31659997e-01, -3.75279993e-01,
        2.90679991e-01,  2.30320007e-01,  1.81250006e-01,  4.02009994e-01,
        1.35179996e-01, -1.95620000e-01,  3.06389987e-01, -1.32390007e-01,
        6.78969979e-01,  4.22340006e-01,  3.26370001e-01, -1.52810007e-01,
        3.76980007e-01, -2.33030006e-01, -3.38169992e-01,  3.05880010e-01,
        4.49180007e-01, -8.36239994e-01,  5.91459990e-01,  2.49579996e-01,
        3.99859995e-01, -5.01720011e-01, -2.35440001e-01, -1.46960005e-01,
       -3.51440012e-01, -5.68520010e-01,  8.95399973e-02,  8.26120019e-01,
       -2.65859991e-01,  3.90300006e-01, -3.68489996e-02,  4.82569993e-01,
        7.16639996e-01,  1.10040002e-01, -5.93540013e-01, -3.32159996e-01,
       -2.57360011e-01, -3.45310003e-01, -2.63260007e-02, -2.37470001e-01,
        1.96559995e-04, -2.74800003e-01,  3.85120004e-01, -3.95810008e-01,
        1.14040002e-01, -2.51740009e-01, -3.24699998e-01,  8.96079987e-02,
        2.49290004e-01,  

In [ ]:
padded_docs.shape[1]

20

In [ ]:
W2Vec_Data=pd.DataFrame()
for i in range(padded_docs.shape[0]):
  Sentence = np.zeros(100)
  for j in range(padded_docs.shape[1]):
    Sentence=Sentence+embedding_matrix_vocab[padded_docs[i][j]]
  W2Vec_Data=W2Vec_Data.append(pd.DataFrame([Sentence]))



In [ ]:
W2Vec_Data.shape

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(n_estimators = 50) 
 
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 

RandomForestClassifier(n_estimators=50)

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83      3529
           1       0.85      0.69      0.76      1705
           2       0.90      0.88      0.89      2105
           3       0.91      0.79      0.85      1820

    accuracy                           0.84      9159
   macro avg       0.86      0.82      0.83      9159
weighted avg       0.84      0.84      0.83      9159



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 100)            892100    
                                                                 
 flatten (Flatten)           (None, 400)               0         
                                                                 
 dense (Dense)               (None, 1)                 401       
                                                                 
Total params: 892,501
Trainable params: 401
Non-trainable params: 892,100
_________________________________________________________________
None


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(W2Vec_Data, sf,test_size=0.33,
                                                    random_state=1)

In [ ]:

clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.79      0.81      3529
           1       0.73      0.75      0.74      1705
           2       0.85      0.87      0.86      2105
           3       0.82      0.86      0.84      1820

    accuracy                           0.82      9159
   macro avg       0.81      0.82      0.81      9159
weighted avg       0.82      0.82      0.82      9159



Accuracy: 96.102387


In [ ]:
from sklearn.svm import LinearSVC


In [ ]:
lsvc = LinearSVC(verbose=0)

In [ ]:
lsvc.fit(W2Vec_Data, sf)




/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC()

In [ ]:
y_pred=lsvc.predict(W2Vec_Data)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(sf, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.76      0.77     10562
           1       0.73      0.69      0.71      5304
           2       0.75      0.92      0.83      6221
           3       0.84      0.73      0.78      5667

    accuracy                           0.78     27754
   macro avg       0.78      0.77      0.77     27754
weighted avg       0.78      0.78      0.77     27754



In [ ]:
from gensim.models.poincare import PoincareModel, PoincareRelations
from gensim.test.utils import datapath


In [ ]:
file_path = datapath('/content/drive/MyDrive/BTP/ecommerceDataset.csv')
#model = PoincareModel(PoincareRelations(file_path), negative=2)


In [ ]:
model

In [ ]:
model.train(epochs=50)

In [ ]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('/content/drive/MyDrive/BTP/poincare_glove_50x2D_cosh-dist-sq_init_trick.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 189534 word vectors.


In [ ]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [ ]:
embedding_matrix

array([[ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.024,  0.019,  0.096, ...,  0.07 , -0.009,  0.142],
       [ 0.042,  0.026,  0.077, ...,  0.07 , -0.079,  0.09 ],
       ...,
       [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ]])

In [ ]:

def embedding_for_vocab(filepath, word_index,
						embedding_dim):
	vocab_size = len(word_index) + 1
	
	# Adding again 1 because of reserved 0 index
	embedding_matrix_vocab = np.zeros((vocab_size,
									embedding_dim))

	with open(filepath, encoding="utf8") as f:
		for line in f:
			word, *vector = line.split()
			if word in word_index:
				idx = word_index[word]
				embedding_matrix_vocab[idx] = np.array(
					vector, dtype=np.float32)[:embedding_dim]

	return embedding_matrix_vocab


# matrix for vocab: word_index
embedding_dim = 100
embedding_matrix_vocab = embedding_for_vocab(
	'/content/drive/MyDrive/BTP/poincare_glove_50x2D_cosh-dist-sq_init_trick.txt', t.word_index,
embedding_dim)

print("Dense vector for first word is => ",
	embedding_matrix_vocab[3])


Dense vector for first word is =>  [ 0.042  0.013  0.178  0.066 -0.083 -0.021  0.046 -0.024  0.026  0.095
  0.064 -0.109  0.049  0.028 -0.052 -0.046 -0.026 -0.08   0.087  0.006
  0.097 -0.034 -0.087 -0.015  0.014  0.13   0.073 -0.01   0.003 -0.123
  0.064  0.028 -0.002 -0.064 -0.105 -0.041  0.018  0.012  0.015 -0.026
 -0.085  0.032  0.035  0.007  0.03  -0.074 -0.082 -0.024 -0.069 -0.063
 -0.064  0.009 -0.082 -0.118 -0.11  -0.033 -0.108 -0.094  0.007 -0.121
  0.003 -0.062  0.053 -0.029 -0.017 -0.091  0.087 -0.123 -0.066 -0.081
 -0.031 -0.079  0.068 -0.101 -0.02  -0.078 -0.029  0.052 -0.014  0.025
  0.054 -0.083  0.055 -0.114 -0.037 -0.096 -0.082  0.079  0.092 -0.018
  0.015  0.025  0.061 -0.076 -0.027 -0.035  0.045  0.025 -0.059  0.086]


In [ ]:
W2Ve_Data=pd.DataFrame()
for i in range(padded_docs.shape[0]):
  Sentenc = np.zeros(100)
  for j in range(padded_docs.shape[1]):
    Sentenc=Sentenc+embedding_matrix_vocab[padded_docs[i][j]]
  W2Ve_Data=W2Ve_Data.append(pd.DataFrame([Sentenc]))



In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(W2Ve_Data, sf,test_size=0.33,
                                                    random_state=1)

In [ ]:

clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83      3529
           1       0.80      0.72      0.76      1705
           2       0.89      0.90      0.90      2105
           3       0.89      0.78      0.83      1820

    accuracy                           0.83      9159
   macro avg       0.84      0.82      0.83      9159
weighted avg       0.84      0.83      0.83      9159



In [ ]:
clf = RandomForestClassifier(n_estimators = 50) 
 
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 

RandomForestClassifier(n_estimators=50)

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.91      0.82      3529
           1       0.84      0.66      0.74      1705
           2       0.91      0.88      0.89      2105
           3       0.91      0.76      0.83      1820

    accuracy                           0.82      9159
   macro avg       0.85      0.80      0.82      9159
weighted avg       0.83      0.82      0.82      9159



In [ ]:
from sklearn.svm import LinearSVC


In [ ]:
lsvc = LinearSVC(verbose=0)

In [ ]:
lsvc.fit(W2Ve_Data, sf)




/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC()

In [ ]:
y_pred=lsvc.predict(W2Ve_Data)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(sf, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.84      0.80     10562
           1       0.81      0.68      0.74      5304
           2       0.87      0.90      0.89      6221
           3       0.81      0.76      0.78      5667

    accuracy                           0.81     27754
   macro avg       0.81      0.79      0.80     27754
weighted avg       0.81      0.81      0.80     27754



In [ ]:
from sklearn.model_selection import cross_val_score


In [ ]:
lsvc = LinearSVC(C=1, random_state=42,scoring='accuracy')

In [ ]:

scores = cross_val_score(lsvc, W2Ve_Data, sf, cv=5)
scores


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


array([0.77733742, 0.77643668, 0.81030445, 0.78346244, 0.79063063])

In [ ]:
def loading_embeddings():
    #“”” loading glove embeddings “””
    embeddings_index = {}
    f = open('/content/glove.6B.100d.txt', encoding="utf8") # loading the file
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = coefs
    f.close()
    return embeddings_index

In [ ]:
from keras.preprocessing.sequence import pad_sequences


ImportError: ignored

ImportError: ignored

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2022-11-15 05:34:41--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2022-11-15 05:34:41--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2022-11-15 05:34:41--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [ ]:
embeddings_index = dict()
f = open('/content/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [ ]:
MAX_NB_WORDS = 100000
def prepare_embedding_matrix(word_index):
   # “”” preparing embedding matrix with our data set “””
    embeddings_index = loading_embeddings()
    num_words = min(MAX_NB_WORDS, len(word_index))
    embedding_matrix = np.zeros((num_words + 1, EMBEDDING_DIM))
    for word, i in word_index.items():
        if i >= MAX_NB_WORDS:
            continue
        embedding_vector = embeddings_index.get(word)
        if embedding_vector is not None:
            # words not found in embedding index will be all-zeros.
            embedding_matrix[i] = embedding_vector
    return embedding_matrix, num_words

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation


In [ ]:
MAX_SEQUENCE_LENGTH = 1000
VALIDATION_SPLIT = 0.1
def vectorizing_data(df):
    #“”” vectorizing and splitting the data for training, testing, validating “””
    label_s = df['v1'].tolist()
    l = list(set(label_s))
    l.sort()
    labels_index = dict([(j,i) for i, j in enumerate(l)])
    labels = [labels_index[i] for i in label_s]
    print('Found %s texts.' % len(df['v2']))
    print('labels_index — ', labels_index)
    tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
    tokenizer.fit_on_texts(df['v2'])
    sequences = tokenizer.texts_to_sequences(df['v2'])
    word_index = tokenizer.word_index
    print('Found %s unique tokens.' % len(word_index))
    df = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
    labels = to_categorical(np.asarray(labels))
    # randomizing and splitting the df into a training set, test set and a validation set
    indices = np.arange(df.shape[0])
    np.random.shuffle(indices)
    df = df[indices]
    labels = labels[indices]
    num_validation_samples = int(VALIDATION_SPLIT * df.shape[0])
    x_train = df[:-num_validation_samples]
    y_train = labels[:-num_validation_samples]
    x_val = df[-num_validation_samples:]
    y_val = labels[-num_validation_samples:]
    x_test = x_train[-num_validation_samples:]
    y_test = y_train[-num_validation_samples:]
    return x_train, y_train, x_test, y_test, x_val, y_val, word_index

In [ ]:
EMBEDDING_DIM = 100
def model_generation(embedding_matrix, num_words):
    #“”” model generation “””
    embedding_layer = Embedding(num_words + 1,
                                EMBEDDING_DIM,
                                weights=[embedding_matrix],
                                input_length=MAX_SEQUENCE_LENGTH,
                                trainable=False)
    convs = []
    filter_sizes = [3,4,5]
    sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
    embedded_sequences = embedding_layer(sequence_input)
    for fsz in filter_sizes:
        l_conv = Conv1D(filters=128, kernel_size=fsz, activation='relu')(embedded_sequences)
        l_pool = MaxPooling1D(5)(l_conv)
        convs.append(l_pool)
    l_merge = Concatenate(axis=1)(convs)
    l_cov1= Conv1D(filters=128, kernel_size=5, activation='relu')(l_merge)
    l_cov1 = Dropout(0.2)(l_cov1)
    l_pool1 = MaxPooling1D(5)(l_cov1)
    l_cov2 = Conv1D(filters=128, kernel_size=5, activation='relu')(l_pool1)
    l_cov2 = Dropout(0.2)(l_cov2)
    l_pool2 = MaxPooling1D(30)(l_cov2)
    l_flat = Flatten()(l_pool2)
    l_dense = Dense(128, activation=’relu’)(l_flat)
    preds = Dense(label_count, activation=’softmax’)(l_dense)
    model = Model(sequence_input, preds)
    return model